<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'adamquaile.fieldset.type' shared service.

return $this->services['adamquaile.fieldset.type'] = new \AdamQuaile\Bundle\FieldsetBundle\Form\FieldsetType();
