<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Vich\UploaderBundle\Naming\Base64Namer' shared service.

return $this->services['Vich\UploaderBundle\Naming\Base64Namer'] = new \Vich\UploaderBundle\Naming\Base64Namer();
