<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'directory_platform.user_subscriber' shared service.

return $this->services['directory_platform.user_subscriber'] = new \DirectoryPlatform\AppBundle\EventListener\UserSubscriber($this);
