<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'payum.command.create_notify_token' shared service.

$this->services['payum.command.create_notify_token'] = $instance = new \Payum\Bundle\PayumBundle\Command\CreateNotifyTokenCommand();

$instance->setContainer($this);
$instance->setName('payum:security:create-notify-token');

return $instance;
