<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'payum.form.type.credit_card' shared service.

return $this->services['payum.form.type.credit_card'] = new \Payum\Core\Bridge\Symfony\Form\Type\CreditCardType();
