<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'payum' shared service.

return $this->services['payum'] = ${($_ = isset($this->services['payum.builder']) ? $this->services['payum.builder'] : $this->load('getPayum_BuilderService.php')) && false ?: '_'}->getPayum();
