<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'payum.security.token_storage' shared service.

return $this->services['payum.security.token_storage'] = new \Payum\Core\Bridge\Doctrine\Storage\DoctrineStorage(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'}, 'DirectoryPlatform\\AppBundle\\Entity\\PaymentToken');
