<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'vich_uploader.namer_uniqid.avatar_image' shared service.

return $this->services['vich_uploader.namer_uniqid.avatar_image'] = new \Vich\UploaderBundle\Naming\UniqidNamer();
