<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'payum.extension.storage.directoryplatform_appbundle_entity_payment' shared service.

return $this->services['payum.extension.storage.directoryplatform_appbundle_entity_payment'] = new \Payum\Core\Extension\StorageExtension(${($_ = isset($this->services['payum.storage.directoryplatform_appbundle_entity_payment']) ? $this->services['payum.storage.directoryplatform_appbundle_entity_payment'] : $this->load('getPayum_Storage_DirectoryplatformAppbundleEntityPaymentService.php')) && false ?: '_'});
