<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'payum.extension.log_executed_actions' shared service.

return $this->services['payum.extension.log_executed_actions'] = new \Payum\Core\Bridge\Psr\Log\LogExecutedActionsExtension(${($_ = isset($this->services['monolog.logger.payum']) ? $this->services['monolog.logger.payum'] : $this->load('getMonolog_Logger_PayumService.php')) && false ?: '_'});
