<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'payum.listener.reply_to_http_response' shared service.

return $this->services['payum.listener.reply_to_http_response'] = new \Payum\Bundle\PayumBundle\EventListener\ReplyToHttpResponseListener(${($_ = isset($this->services['payum.converter.reply_to_http_response']) ? $this->services['payum.converter.reply_to_http_response'] : ($this->services['payum.converter.reply_to_http_response'] = new \Payum\Core\Bridge\Symfony\ReplyToSymfonyResponseConverter())) && false ?: '_'});
