<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'payum.command.debug_gateway' shared service.

$this->services['payum.command.debug_gateway'] = $instance = new \Payum\Bundle\PayumBundle\Command\DebugGatewayCommand();

$instance->setContainer($this);
$instance->setName('debug:payum:gateway');

return $instance;
