<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'payum.extension.logger' shared service.

return $this->services['payum.extension.logger'] = new \Payum\Core\Bridge\Psr\Log\LoggerExtension(${($_ = isset($this->services['monolog.logger.payum']) ? $this->services['monolog.logger.payum'] : $this->load('getMonolog_Logger_PayumService.php')) && false ?: '_'});
